# Generated by Django 5.2.3 on 2025-08-21 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PlanetDiscovery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "method",
                    models.CharField(help_text="Discovery method", max_length=100),
                ),
                (
                    "year",
                    models.IntegerField(
                        blank=True, help_text="Year of discovery", null=True
                    ),
                ),
                (
                    "locale",
                    models.CharField(
                        help_text="Location of observation (Ground or Space)",
                        max_length=50,
                    ),
                ),
                (
                    "facility",
                    models.CharField(help_text="Name of facility", max_length=100),
                ),
            ],
            options={
                "verbose_name": "Planet Discovery",
                "verbose_name_plural": "Planet Discoveries",
                "db_table": "planet_discoveries",
            },
        ),
        migrations.CreateModel(
            name="Star",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the star", max_length=100, unique=True
                    ),
                ),
                (
                    "spect_type",
                    models.CharField(
                        blank=True, help_text="Spectral type", max_length=30, null=True
                    ),
                ),
                (
                    "mass",
                    models.FloatField(
                        blank=True, help_text="Mass in solar masses", null=True
                    ),
                ),
                (
                    "radius",
                    models.FloatField(
                        blank=True, help_text="Radius in solar radii", null=True
                    ),
                ),
                (
                    "temperature",
                    models.FloatField(
                        blank=True, help_text="Effective temperature (K)", null=True
                    ),
                ),
                (
                    "luminosity",
                    models.FloatField(
                        blank=True, help_text="Amount of energy emitted", null=True
                    ),
                ),
                ("age", models.FloatField(blank=True, help_text="Age", null=True)),
            ],
            options={
                "db_table": "stars",
            },
        ),
        migrations.CreateModel(
            name="StarSystem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the system", max_length=100, unique=True
                    ),
                ),
                (
                    "num_stars",
                    models.IntegerField(
                        blank=True, help_text="Number of stars", null=True
                    ),
                ),
                (
                    "num_planets",
                    models.IntegerField(
                        blank=True, help_text="Number of planets", null=True
                    ),
                ),
                (
                    "num_moons",
                    models.IntegerField(
                        blank=True, help_text="Number of moons", null=True
                    ),
                ),
                (
                    "distance",
                    models.FloatField(
                        blank=True,
                        help_text="Distance from Earth in parsecs",
                        null=True,
                    ),
                ),
                (
                    "ra",
                    models.FloatField(
                        blank=True, help_text="Right Ascension", null=True
                    ),
                ),
                (
                    "dec",
                    models.FloatField(blank=True, help_text="Declination", null=True),
                ),
            ],
            options={
                "verbose_name": "Star System",
                "verbose_name_plural": "Star Systems",
                "db_table": "star_systems",
            },
        ),
        migrations.CreateModel(
            name="Planet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the planet", max_length=100, unique=True
                    ),
                ),
                (
                    "orbital_period",
                    models.FloatField(
                        blank=True, help_text="Orbital period in days", null=True
                    ),
                ),
                (
                    "radius_earth",
                    models.FloatField(
                        blank=True, help_text="Radius in Earth radii", null=True
                    ),
                ),
                (
                    "mass_earth",
                    models.FloatField(
                        blank=True, help_text="Mass in Earth masses", null=True
                    ),
                ),
                (
                    "equilibrium_temperature",
                    models.FloatField(
                        blank=True, help_text="Temperature in Kelvin", null=True
                    ),
                ),
                (
                    "semi_major_axis",
                    models.FloatField(
                        blank=True, help_text="Distance from star in AU", null=True
                    ),
                ),
                (
                    "insolation_flux",
                    models.FloatField(
                        blank=True, help_text="Flux relative to Earth = 1.0", null=True
                    ),
                ),
                (
                    "orbital_eccentricity",
                    models.FloatField(
                        blank=True,
                        help_text="Orbital deviation from a circle",
                        null=True,
                    ),
                ),
                (
                    "discovery",
                    models.ForeignKey(
                        blank=True,
                        help_text="Planet discovery",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.planetdiscovery",
                    ),
                ),
                (
                    "host_star",
                    models.ForeignKey(
                        help_text="The host star",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.star",
                    ),
                ),
            ],
            options={
                "db_table": "planets",
            },
        ),
        migrations.AddField(
            model_name="star",
            name="system",
            field=models.ForeignKey(
                help_text="The system",
                on_delete=django.db.models.deletion.CASCADE,
                to="api.starsystem",
            ),
        ),
    ]
