# Generated by Django 5.2.3 on 2025-09-12 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planet',
            old_name='equilibrium_temperature',
            new_name='equilibrium_temperature_k',
        ),
        migrations.RenameField(
            model_name='planet',
            old_name='insolation_flux',
            new_name='insolation_flux_earth',
        ),
        migrations.RenameField(
            model_name='planet',
            old_name='orbital_period',
            new_name='orbital_period_days',
        ),
        migrations.RenameField(
            model_name='planet',
            old_name='semi_major_axis',
            new_name='semi_major_axis_au',
        ),
        migrations.RenameField(
            model_name='star',
            old_name='temperature',
            new_name='effective_temperature_k',
        ),
        migrations.RenameField(
            model_name='star',
            old_name='luminosity',
            new_name='luminosity_sun',
        ),
        migrations.RenameField(
            model_name='star',
            old_name='mass',
            new_name='mass_sun',
        ),
        migrations.RenameField(
            model_name='star',
            old_name='radius',
            new_name='radius_sun',
        ),
        migrations.RenameField(
            model_name='star',
            old_name='spect_type',
            new_name='spectral_type',
        ),
        migrations.RenameField(
            model_name='starsystem',
            old_name='distance',
            new_name='distance_parsecs',
        ),
        migrations.RemoveField(
            model_name='star',
            name='age',
        ),
        migrations.AddField(
            model_name='star',
            name='age_gya',
            field=models.FloatField(blank=True, help_text='Age in Giga Years', null=True),
        ),
        migrations.AlterField(
            model_name='star',
            name='system',
            field=models.ForeignKey(help_text='The host star system', on_delete=django.db.models.deletion.CASCADE, to='api.starsystem'),
        ),
        migrations.AlterField(
            model_name='starsystem',
            name='name',
            field=models.CharField(help_text='Name of the star system', max_length=100, unique=True),
        ),
    ]
