# Generated by Django 5.2.3 on 2025-06-20 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('mass', models.FloatField(help_text='Mass in solar masses', null=True)),
                ('radius', models.FloatField(help_text='Radius in solar radii', null=True)),
                ('temperature', models.FloatField(help_text='Effective temperature (K)', null=True)),
                ('distance', models.FloatField(help_text='Distance from Earth in parsecs', null=True)),
                ('ra', models.FloatField(help_text='Right Ascension', null=True)),
                ('dec', models.FloatField(help_text='Declination', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('orbital_period', models.FloatField(help_text='Orbital period in days', null=True)),
                ('radius', models.FloatField(help_text='Radius in Earth radii', null=True)),
                ('mass', models.FloatField(help_text='Mass in Earth masses', null=True)),
                ('equilibrium_temperature', models.IntegerField(help_text='Temperature in Kelvin', null=True)),
                ('semi_major_axis', models.FloatField(help_text='Distance from star in AU', null=True)),
                ('discovery_method', models.CharField(blank=True, max_length=100, null=True)),
                ('discovered_year', models.IntegerField(null=True)),
                ('insolation_flux', models.FloatField(help_text='Flux relative to Earth = 1.0', null=True)),
                ('host_star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planets', to='planets.star')),
            ],
        ),
    ]
