# Generated by Django 5.2.3 on 2025-06-25 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='discovery',
            field=models.ForeignKey(blank=True, help_text='Planet discovery', null=True, on_delete=django.db.models.deletion.CASCADE, to='planets.planetdiscovery'),
        ),
    ]
