# Generated by Django 5.2.3 on 2025-06-26 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0002_alter_planet_discovery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='equilibrium_temperature',
            field=models.FloatField(blank=True, help_text='Temperature in Kelvin', null=True),
        ),
    ]
