# Generated by Django 5.2.3 on 2025-07-21 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planets", "0003_alter_planet_equilibrium_temperature"),
    ]

    operations = [
        migrations.AddField(
            model_name="planet",
            name="orbital_eccentricity",
            field=models.FloatField(
                blank=True, help_text="Orbital deviation from a circle", null=True
            ),
        ),
        migrations.AddField(
            model_name="star",
            name="age",
            field=models.FloatField(blank=True, help_text="Age", null=True),
        ),
        migrations.AddField(
            model_name="star",
            name="luminosity",
            field=models.FloatField(
                blank=True, help_text="Amount of energy emitted", null=True
            ),
        ),
    ]
