# Generated by Django 5.2.3 on 2025-08-06 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("planets", "0004_planet_orbital_eccentricity_star_age_star_luminosity"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="planet",
            table="planets",
        ),
        migrations.AlterModelTable(
            name="planetdiscovery",
            table="planet_discoveries",
        ),
        migrations.AlterModelTable(
            name="star",
            table="stars",
        ),
        migrations.AlterModelTable(
            name="starsystem",
            table="star_systems",
        ),
    ]
