# Generated by Django 5.2.3 on 2025-07-30 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulations", "0002_alter_simulationrun_simulation_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="simulationrun",
            name="simulation_type",
            field=models.CharField(
                choices=[
                    ("TRAVEL_TIME", "Travel Time"),
                    ("SEASONAL_TEMPS", "Seasonal Temperatures"),
                    ("TIDAL_LOCKING", "Tidal Locking"),
                    ("STAR_LIFETIME", "Star Lifetime"),
                ],
                max_length=50,
            ),
        ),
    ]
